[platformio]
default_envs = esp32s3dev

[env:esp32s3dev]
platform = espressif32@~6.3.2
board = esp32s3dev
framework = arduino
build_flags = 
  -DARDUINO_ARCH_ESP32
  -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
  https://github.com/pbolduc/AsyncTCP.git @ 1.2.0
  https://github.com/lorol/LITTLEFS.git
  ${env.lib_deps}

monitor_speed = 115200
upload_speed = 921600

[env:esp32s3dev_audioreactive]
extends = esp32s3dev
build_flags = ${env.build_flags} 
  -D USERMOD_AUDIOREACTIVE
  -D FFT_SPEED_OVER_PRECISION
  -D USERMOD_PWM_OUTPUTS
  -D USERMOD_PWM_OUTPUT_PINS=5

lib_deps = ${env.lib_deps} 
  kosme/arduinoFFT @ 2.0.1